# Generated by Django 4.2 on 2023-04-05 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название уровня задачи')),
                ('color', models.CharField(help_text='Вводить в формате #FFFFFF', max_length=7, verbose_name='Цвет уровня задачи')),
            ],
            options={
                'verbose_name': 'Уровень задачи',
                'verbose_name_plural': 'Уровни задачи',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название команды')),
                ('members', models.ManyToManyField(related_name='team', to=settings.AUTH_USER_MODEL, verbose_name='Участники команды')),
            ],
            options={
                'verbose_name': 'Команда разработчиков',
                'verbose_name_plural': 'Команды разработчиков',
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название списка задач')),
                ('color', models.CharField(help_text='Вводить в формате #FFFFFF', max_length=7, verbose_name='Цвет списка задачи')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team', verbose_name='Команда разработчиков')),
            ],
            options={
                'verbose_name': 'Список задач',
                'verbose_name_plural': 'Списки задач',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('is_done', models.BooleanField(default=False, verbose_name='Завершена?')),
                ('date_complete', models.DateField(blank=True, null=True, verbose_name='Дата завершения задачи')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата ожидаемого завершения задачи')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('task_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tasklevel', verbose_name='Уровень задачи')),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tasklist', verbose_name='Список задач')),
            ],
        ),
    ]
